### ISSUE TITLE
z-index issues with latest material-ui and FormControl

### ISSUE THREAD

**Issue by mbyrne00** [iulian-radu-at/react-select-material-ui#28] opened 2020-02-12 23:52 UTC
Hi - material-ui have set a `z-index: 0` on `FormControl` by default with their latest update. I raised an issue with them to state that it will break components like this one: https://github.com/mui-org/material-ui/issues/19677

If they decide not to fix it this library could add `style={{ zIndex: 1 }}` or even `style={{ zIndex: 'unset' }}` to the `FormComponent` it renders to avoid issues where the dropdown appears behind checkboxes.

My workaround is to do this from my calling component for now.

**Comment by oliviertassinari** [comment] 2020-02-13 07:28
Note the introduction of the Autocomplete component in the lab.

**Comment by mbyrne00** [comment] 2020-02-13 21:17
That looks promising @oliviertassinari - I'll take a look at that for new components and see if we can swap over. Thanks.

**Comment by iulian-radu-at** [comment] 2020-03-22 19:24
Hi @mbyrne00,

I added to storybook your issue and it works correctly there.
Please check the code of the storybook for issue#28 and in case your code is "different" than this and the problem is still reproducible by you with the latest version of react-select-material-ui please send me a code which should reproduce it in storybook.

Thanks,
Iulian

**Comment by oliviertassinari** [comment] 2020-03-22 19:46
The issue should have been fixed upstream now.

**Comment by iulian-radu-at** [comment] 2020-03-22 20:08
Thanks @oliviertassinari.

Then I will close this issue.

Cheers,
Iulian

**Closed by iulian-radu-at** 2020-03-22 20:08 UTC
