### ISSUE TITLE
Limit dropdown number

### ISSUE THREAD

**Issue by wakuu** [iulian-radu-at/react-select-material-ui#31] opened 2020-03-20 20:40 UTC
Hi, I'm using your component. It works really well but in my website i have a select with 5000 or more options.
Is there a way to limit dropdown to 100 for example ? Cause my browser really don't like it.
Thanks

**Comment by iulian-radu-at** [comment] 2020-03-22 19:02
Hi @wakuu,

Unfortunately react-select does not provide any option for this use-case.
Also there is no possibility to get the list of filtered options from react-select and to filter it even more (by index for example, so we can display only the first 100).

You can try to implement your own filterOption function which will return only the first 100 matching options.

```
const filterOption = (option: Option, rawInput: string): boolean => {
  ...
};

<ReactSelectMaterialUi
        ...
        SelectProps={{
          filterOption,
          ...
        }}

```

The problem is that you do not know when you start to check the options from beginning or if there are overlapping checks in progress.

So for the moment there is any good solution. Sorry.

Cheers,
Iulian

PS: As such I will close this Issue.

**Closed by iulian-radu-at** 2020-03-22 19:02 UTC
