### ISSUE TITLE
Value prop shows in input text instead of label

### ISSUE THREAD

**Issue by arturoribessanz** [iulian-radu-at/react-select-material-ui#20] opened 2019-09-11 11:00 UTC
I am using `SingleSelect`. When options are provided as an array of objects having a different label/value (for example `{value: 1239, value: 'Harold'}`, when I pass 1239 as `value` prop, it shows 1239 in the input field, but the correct "Harold" option is selected when the component is opened.

Here I provide some code to reproduce the issue.

```
class TestComponent extends Component {
    state = {
        value: '2',
    };

    render () {
        return (
            <SingleSelect
                value={this.state.value}
                onChange={(value) => {
                    this.setState({value})
                }}
                options={[{value: '1', label: 'one'}, {value: '2', label: 'two'}, {value: '3', label: 'three'}]}
            />);
    }
}
```

**Comment by iulian-radu-at** [comment] 2019-09-15 08:46
@arturoribessanz I added your test code to storybook and also in a new created app with create-react-app and it works in both places as expected. So I cannot reproduce your problem with your code.

Please try your code with the latest version of react-select-material-ui and let me know if works. 

Thanks.

**Comment by iulian-radu-at** [comment] 2019-09-22 08:15
Closed as there was no feedback from the issue reporter

**Closed by iulian-radu-at** 2019-09-22 08:15 UTC
